-- Template slot schema.
-- Applied 2026-05-18. Idempotent.
--
-- documents.template_schema stores a JSON object describing each
-- placeholder slot in a template document. Keys are slot names
-- (e.g. "SELLER_NAME"), values are { type, role, hint } objects
-- describing the slot's semantics. The slot resolver in
-- /vault/fill-template uses this metadata to disambiguate matches
-- when multiple candidates exist.
--
-- Populated two ways:
--   1. Auto on generate_docx — Mike scans the generated bytes for
--      {SLOT_NAME} placeholders and writes a minimal schema with
--      type='any'.
--   2. Explicitly via the new define_template_schema(doc_id, schema)
--      chat tool — the cloud LLM can enrich the schema with type/role
--      hints after drafting the template.

alter table public.documents
  add column if not exists template_schema jsonb;
